### PR TITLE
Setter/Getter support

### PR DESCRIPTION
**Pull request by AlexTrotsenko**
1. JSGetter and JSSetter annotations are added
2. Support for "is" getter is added
3. Setter/getter-related logic is simplified and encapsulated
4. New are tests and existing are updated

### CODE REVIEW

**Comment by Mizumi** [comment]
This is a wonderful PR - thank you so much for your work! 

There are some minor changes that I would like to see before it's merged (all of your code looks fine, I think), but I can easily do these for you if you don't have time:

-  I would like *new* files to have no license headers and have the author of the file and their email address in the Javadoc for the file's class (e.g., `@author Alex Trotsenko [alex@acme.com]`). This allows us to maintain a consistent license project-wide while also guaranteeing authors of new work are appropriately credited.

- All new methods and classes (regardless of access level) should have a "complete" JavaDoc. This means that there should be a brief description, `@param` descriptions for each argument (no matter how obvious), `@return` descriptions for the return value (if non-void), and `@throws` descriptions for all exceptions thrown.

Please let me know if you think this is an acceptable approach moving forward; I would very much like your feedback on this. The biggest mystery for my is how to reliably handle the licensing of contributions from everyone; I don't want to get caught up in a mess of CLAs, but I also don't want anyone's contributions to go without credit or get caught up in some licensing technicality down the road.

If you think these changes are appropriate, I will go ahead and put them into a formalized `CONTRIBUTING.md` document - we're definitely going to want one of those on this project!!

**Comment by AlexTrotsenko** [comment]
@Mizumi thanks for the review of PR and your kind feedback. 
All your suggestions concerning `@author` and JavaDoc are fine for me and I will do requested changes.
As for the licensing: thanks for carrying about contributions. Also I don't have any preferable approach for such projects under BSD 3-like licences, so any your suggestions are fine for me.

**Comment by Mizumi** [comment]
@AlexTrotsenko No problem; I'm delighted to have your contributions become a part of this young project. 

Regarding licensing, I'll proceed with the current BSD 3-Clause with no individual copyrights on files. If we run into trouble down the road, we can migrate to an Apache V2 and hope for the best. 😉

**Comment by AlexTrotsenko** [comment]
@Mizumi I did the changes you was asking about. Hope, all should be fine now.

**Comment by Mizumi** [comment]
Looks good! I made some minor changes to commenting for consistency; post-merge I will go through and clean up the rest of the JavaDocs.

One thing I noticed just now is that the annotation support essentially forces users to manually "wire in" JS Getter and Setter properties. I find this behavior inconsistent with the project's goal of seamlessly injecting Java features; perhaps we could have the following behavior instead:

- All methods that follow the Java Getter/Setter naming convention will be automatically registered as JS getters and setters.

- All methods that have annotations will be automatically registered as JS getters and setters regardless of their names.

- If a user wishes, there can be a flag somewhere that lets only getters and setters that are annotated be registered.

What do you think of this behavior? If it seems unusual, please let me know.

**Comment by AlexTrotsenko** [comment]
@Mizumi I really share your view of seamlessly injecting Java in JS. 
The only question for me here is the expected result of injection Java object with getter/setter method.
Actually, I also intended to discuss current behaviour with you.

Initially I though of following default behaviour:
 - Injection of Java object with getter/setter results in JS object getter/setter method. 
 - Adding `@JSGetter` / `@JSSetter ` annotation creates property with setter/getter bind to Java methods.
- Same time adding `@JSGetter` / `@JSSetter ` annotation removes getter/setter method _(I have not implemented this as was not sure if it's really good idea)_.

After checking your approach I generally like it more. The only thing, which I would add/change: 
-  instead of flag introduce annotation, called something like `@ExportStratagy` or `@JSExport`. This way we can customise how both setter/getter and all other methods are exported and change the defaults. 

I guess, that it would be nice to customise export behaviour with following options:
 - as method
 - as property
 - as both method and property
 - do not export intentionally

What do you thing about this suggestions?

**Comment by Mizumi** [comment]
I think having options for export behavior would be valuable, especially for controlling API visibility and so on. However, I do want to avoid adding too many options to this adapter right now; perhaps we could put off this kind of advanced configuration until we finish the basic functionality?

I think your idea of using an annotation to configure exports is good! My one concern is that it could again force users to clutter their code with annotations, and that can pose issues if they are trying to inject a class they do not own (e.g., a class from the Java utils). Thus my preference for a flag instead of an annotation. This is sort of how I would envision it working:

```
// Create Runtime
V8 v8 = V8.createRuntime();

// Inject a class, automatically detecting all getters and setters (default behavior).
V8JavaAdapter.injectClass(Foo.class, v8, true);

// Inject a class, only detecting annotated getters and setters.
V8JavaAdapter.injectClass(Bar.class, v8, false);
```

This could raise some questions on considering some kind of `V8JavaAdapterConfiguration` class down the line, but at this point this may offer a very nice solution to this problem. Do you agree, or do you think there's a better way around this?

Also completely unrelated: I forgot about adding validation to these methods. Specifically, any method (whether automatically detected by its name or annotated) should conform to the following rules:

- Getters should have a `void` return type and accept exactly one argument.
- Setters should have a non-`void` return type and accept no arguments.

This is relatively trivial to confirm since we already have a reference to the method's metadata, but it *is* a minor oversight in the current implementation.

**Comment by Mizumi** [comment]
Another idea: With all this talk of annotations, we could introduce a `@JSMethod` annotation as another feature to allow customization. If a class uses this annotation (or some configuration option is set per my previous comment), only methods that have that annotation (getters and setters included) will be injected into the V8 context. What do you think?

**Comment by AlexTrotsenko** [comment]
Hi @Mizumi, concerning `@JSMethod` - I fully agree that it would nice to have it.  Also I think, that we could add `"@JSIgnore"` annotations in order to provide ability to  prevent _"undesired"_ methods from being exported to JS.  _(In fact, that's exactly the behaviour, which I meant, talking about `@ExportStratagy` - either 4 different annotations or one single annotation with 4 possible values. All in all, different annotations looks more expressive rather then single `@ExportStratagy` - so let's use them instead)_.

 Concerning "flag" - thanks for detailed explanation regarding your vision of it. Now I see the reason - injection of 3rd party classes. I do agree, that we should try to kept the initial ability of exporting classes without any annotations - regardless whether we are adding new functionality like Getters/Setters. The only question for me whether it is the necessary to have the flag in ".inject" api. In the currently suggested behaviour:
1. if it's 3rd party classes - then we can't add any annotations - so `"flag"` must be always `"true"`
2. If it's our classes - then we can add annotations -  and thus `"flag"` could be `"true"` or `"false"`.

Thus, while flag looks fine, I personally would prefer to introduce class-level annotation like `@JSIgnoreNotAnotated` instead of the flag. This way for 3rd party classes - "flagged value" _(detect automatically)_ is always `"true"`. Also by default it's also `"true"` for our classes. The value became `"false"` only when this annotation is present on the class. As for me, the benefits of this approach:
- no necessity to have annotations  for 3rd party classes and our own classes
- those, who don't want to deal with annotations -  don't need to deal with `true`/`false` flags. 
- those, who adds annotations to the methods of the class - don't need to remember to put `"false"` flag in `.injectObject`, which is in the different place. Also all annotation-related data is incapsulated in one class and do not present in the in ".inject" api.

What do you think about the suggested approach?

P.S. I haven't replied early as I had much to do these days. Now I am happy to do before-mentioned  changes if they are looks good for you.

**Pull request merged**
