### PR TITLE
#11 Added ability of custom handling of return type from methods of injected objects (E.g. List/Map)

### PR DESCRIPTION
**Pull request by AlexTrotsenko**
by V8JavaAdapter.setJsTransformation(V8, T.class, new JavaToJsTransformation<T>() {})

### CODE REVIEW

**Comment by AlexTrotsenko** [comment]
Thank you, np with delays. 
Just to mention - this api only changes transformation of return values from the methods of injected Java classes, but not injection of Java object.

E.g.  given:
```
class MapProvider {
      Map provideMap() {...}
}
```

Then following transformation will affect only return value of `MapProvider.provideMap()`, but not `V8JavaAdapter.injectObject(v8, new Map())`
```
V8JavaAdapter.setJsTransformation(v8, Map.class, javaObject -> V8ObjectUtils.toV8Array(v8, javaObject) )
```

I have implemented it as it's minimal functionality need for me.

If you think, that ability to "override" transformation of injected objects as well is also a good idea - then  api could be changed to something like:
`V8JavaAdapter.injectClass(v8, Class, JavaToJsTransformation)`

**Comment by crahda** [comment]
On further inspection, this eerily resembles the interception API that we have already (see `src/main/java/io/alicorn/v8/V8JavaClassInterceptor.java`). Can you confirm this and then re-open this if the interceptor API does not meet your needs?

**Comment by AlexTrotsenko** [comment]
@crahda thanks for info, I will check `V8JavaClassInterceptor` !

**Comment by AlexTrotsenko** [comment]
@crahda I have tested suggested solution with `V8JavaClassInterceptor.java `.

Indeed, I was able to achieve the goal without adding new `"JsTransformation"` api. 
The only thing, that I need _java object_ during construction of _JS Object_ in `.getConstructorScriptBody() `, but not afterwards. Also `onInject()` call does not work for such case: I can't create _JS array_ when _Java List_ is injected.
I have already created pull request with the changes - https://github.com/alicorn-systems/v8-adapter/pull/28.

**Pull request closed without merging**
